import type { AnalysisLanguage } from "./analyze-shared";

export type ResearchRule = {
  id: `R${string}`;
  construct: { zh: string; en: string };
  signals: RegExp[];
  counterSignals: RegExp[];
  severity: "low" | "notice" | "pressure" | "high" | "urgent" | "meta";
  explanation: { zh: string; en: string };
  grounding: { zh: string; en: string };
};

const bilingual = (zh: string, en: string) => ({ zh, en });
const rule = (id: ResearchRule["id"], zh: string, en: string, signals: RegExp[], counterSignals: RegExp[], severity: ResearchRule["severity"], explanation: [string, string], grounding: [string, string]): ResearchRule => ({
  id, construct: bilingual(zh, en), signals, counterSignals, severity,
  explanation: bilingual(explanation[0], explanation[1]), grounding: bilingual(grounding[0], grounding[1]),
});

// Compiled from the bundled 38-rule implementation pack. Runtime includes only
// observable conditions, counterevidence, gates and user-facing explanations.
export const RESEARCH_RULES: ResearchRule[] = [
  rule("R01", "普通分歧/合理协商", "ordinary disagreement / negotiation", [/(一起|共同|协商|商量|可以拒绝|由你决定|together|discuss|your choice|may refuse)/i], [/(威胁|惩罚|必须|不准|threat|punish|must|not allowed)/i], "low", ["双方仍在讨论具体事实并保留修正空间。", "The exchange stays with concrete facts and leaves room to revise."], ["不同意见可以存在，不必自动上升为关系定性。", "Disagreement can exist without becoming a verdict on the relationship."]),
  rule("R02", "需求—退缩", "demand–withdraw sequence", [/(反复|一直).{0,12}(不回|沉默|回避)|提出.{0,12}(却|但).{0,12}(不回应|退出)|repeatedly.{0,12}(silent|avoid|withdraw)/i], [/(明天|晚上|稍后).{0,8}(再聊|继续)|tomorrow|resume at/i], "notice", ["议题被提出后，回应反复退出，具体问题没有得到核对。", "After the issue is raised, repeated withdrawal leaves it unresolved."], ["暂停可以健康；关键是有没有明确恢复时间。", "A pause can be healthy when there is a clear return time."]),
  rule("R03", "强制控制候选", "coercive-control candidate", [/(不准|不许|必须).{0,14}(工作|见朋友|出门|用钱|定位|回家)|断钱|查手机|限制离开|must.{0,12}(work|location|friends)|not allowed/i], [/(可随时关闭|可以拒绝|双方同意|your choice|may refuse|mutual consent)/i], "high", ["多个生活领域的选择被持续收窄，并与惩罚或依赖相连。", "Choices across life domains are repeatedly narrowed through punishment or dependency."], ["强标签需要跨句、重复或跨领域证据。", "A strong label requires repeated, cross-sentence, or cross-domain evidence."]),
  rule("R04", "蔑视/人格贬低", "contempt / character devaluation", [/(白眼狼|废物|你是人吗|公主病|没良心|没人要你|蠢|useless|pathetic|ungrateful|no one wants you)/i], [/(这件事|这份报告|这个行为).{0,12}(失望|需要|缺少)|this (task|behaviour)/i], "pressure", ["讨论不再评价具体行为，而是在判定整个人。", "The wording judges the whole person rather than a specific action."], ["一次选择或失误，不等于对整个人的结论。", "One choice or mistake is not a verdict on the whole person."]),
  rule("R05", "伤害否认/事实关闭", "harm denial / fact closure", [/(根本没有|就是没有|没打过|什么时候.{0,8}(打|踢|骂)|不记得.{0,12}(所以|就是).{0,8}没有|never happened|never hit|didn't happen)/i], [/(不记得|记得不同).{0,16}(愿意听|一起核对|查记录)|don't remember.{0,16}(listen|check)/i], "pressure", ["具体经历没有被核对，否认被当成了结论。", "A concrete experience is not examined; denial is treated as the conclusion."], ["不记得可以说明记忆不同，不能单独证明没有发生。", "Not remembering can show a memory difference; it cannot alone prove nothing happened."]),
  rule("R06", "情绪无效化", "emotional invalidation", [/(不准|没资格).{0,8}(难过|哭|生气)|太敏感|矫情|这点事也配哭|too sensitive|no right to feel|shouldn't be upset/i], [/(理解|知道).{0,8}(你难过|你的感受).{0,12}(但|同时)|understand.{0,10}feel/i], "notice", ["这里否定的不是事实判断，而是对方拥有这种感受的资格。", "The response denies the right to feel, not merely the factual interpretation."], ["感受可以被承认，同时事实仍可继续核对。", "Feelings can be acknowledged while facts are still examined."]),
  rule("R07", "现实感削弱/煤气灯候选", "reality erosion / gaslighting candidate", [/(多次|反复|一直).{0,18}(否认|改写|说没讲过)|录音.{0,12}(也|还).{0,12}(否认|假的)|记忆有问题|精神有问题|repeatedly denied|your memory is wrong/i], [/(一次|那天).{0,10}(记得不同|记错)|承认旧说法|different memory|corrected the record/i], "pressure", ["事实或承诺被反复改写，并开始削弱一方对自己判断的信任。", "Facts or promises are repeatedly rewritten in a way that weakens trust in one's own judgment."], ["一次记忆冲突不够；需要重复或系统性证据。", "One memory conflict is not enough; repeated or systematic evidence is required."]),
  rule("R08", "DARVO", "DARVO", [/(根本没有|没做|没有).{0,30}(撒谎|编|冤枉|害我).{0,30}(你才|我们才|我是受害|伤害我们)|didn't.{0,30}(liar|lying).{0,30}(you are the abuser|hurt me)/i], [/(道歉|承担责任|一起核对)|apolog(?:y|ise)|take responsibility/i], "high", ["否认、攻击和角色倒置出现在同一质询链里，原问题因此消失。", "Denial, attack, and role reversal occur in one chain, displacing the original issue."], ["缺少其中任何一环，都只应使用更窄的标签。", "If any element is missing, use a narrower description."]),
  rule("R09", "内疚诱导/道德债务", "guilt induction / moral debt", [/(养你|拉扯大|学费|生活费|付出).{0,24}(不听|良心|白眼狼|必须|所以)|after all we did|raised you.{0,16}(owe|obey|ungrateful)/i], [/(担心|投入很多).{0,16}(但|不过).{0,12}(你决定|由你)|care.{0,12}your choice/i], "pressure", ["过去的付出被换算成当前必须服从的欠账。", "Past care is converted into a debt requiring present obedience."], ["付出可以成立，但不会自动产生替成年人决定的权限。", "Care can be real without granting authority over an adult's decisions."]),
  rule("R10", "撤回爱/条件式归属", "withdrawal of love / conditional belonging", [/(选他|不听|不同意).{0,16}(别回家|没有家|不是家人|断绝关系)|你没有家|没人要你|no family|not welcome home|disown/i], [/(结束关系|暂停联系).{0,20}(安全|伤害|具体原因)|end the relationship.{0,12}reason/i], "high", ["家庭或关系归属被绑定成服从后的奖励。", "Belonging is made conditional on compliance."], ["不同选择不自动等于背叛，也不取消归属价值。", "A different choice is not automatically betrayal."]),
  rule("R11", "权威压制/自主支持缺失", "authority pressure / lack of autonomy support", [/(我是你(妈|爸|父母)|我是领导).{0,18}(必须|听我的|说了算)|because I'm your (parent|boss).{0,18}must/i], [/(把事实列出来|你决定|可以申诉|discuss the facts|your decision)/i], "pressure", ["身份权威替代了理由和协商。", "Status or authority replaces reasons and discussion."], ["权威可以承担责任，但不应取消说明理由和选择空间。", "Authority can carry responsibility without removing reasons or choice."]),
  rule("R12", "惩罚性沉默/排斥", "punitive silence / exclusion", [/(不听话|不道歉).{0,12}(不理你|不回你).{0,12}(一周|几天|长记性)|silent treatment|ignore you to teach/i], [/(需要.{0,8}(小时|时间).{0,12}(继续谈|再聊)|need space.{0,12}(resume|talk))/i], "notice", ["不回应被明确作为惩罚，而不是有恢复时间的暂停。", "Silence is used as punishment rather than a time-limited pause."], ["健康暂停会说明需要多久、何时回来处理问题。", "A healthy pause states how long it will last and when discussion resumes."]),
  rule("R13", "社会孤立/社会虐待", "social isolation", [/(不许|不准|禁止).{0,10}(见|联系).{0,8}(朋友|家人)|见朋友.{0,12}(查手机|断钱|惩罚)|stop seeing friends|cut off friends/i], [/(支持|可以).{0,10}(见朋友|保持联系)|support.{0,8}friends/i], "high", ["外部关系被主动阻断、监视或惩罚。", "Outside relationships are actively blocked, monitored, or punished."], ["希望多陪伴不等于有权缩小对方的支持网络。", "Wanting more time together does not grant control over someone's support network."]),
  rule("R14", "普通预算/财务协商", "ordinary budgeting", [/(一起|共同).{0,12}(预算|算一下|规划)|按收入比例|各自保留|budget together|income proportion|personal allowance/i], [/(批准|不许工作|交出工资|没收|must approve|hand over salary)/i], "low", ["共同核对预算和风险本身可以是负责任的规划。", "Reviewing budgets and risks together can be responsible planning."], ["关键是规则是否透明、双向、可协商。", "The key is whether rules are transparent, reciprocal, and negotiable."]),
  rule("R15", "经济控制/经济虐待", "economic control / abuse", [/(辞掉工作|不许工作|交出工资卡|没收工资|冻结账户|花钱先申请|制造债务|hand over salary|quit your job|freeze account|ask permission to spend)/i], [/(保留账户|保留工作选择|双方透明|keep your account|keep working|mutual budget)/i], "high", ["资源的获得、使用或保有被限制、夺取或强迫交付。", "Access to, use of, or retention of resources is restricted or compelled."], ["普通预算分歧不够；需要客观的资源限制或剥夺。", "A budget disagreement is not enough; objective resource restriction is required."]),
  rule("R16", "数字控制/技术促成虐待", "digital control / technology-facilitated abuse", [/(未经允许|偷偷|强迫|必须).{0,20}(登录账号|改密码|查聊天|开定位|共享位置)|24小时.{0,8}定位|without permission.{0,20}(account|location)|must.{0,24}(share|keep).{0,12}location/i], [/(自愿|同意).{0,12}(可随时关闭|临时查看|可撤回)|consent.{0,12}(turn off|withdraw)/i], "high", ["账号、设备、定位或通讯在缺少自由同意时被侵入或强迫开放。", "Accounts, devices, location, or communications are accessed without free consent."], ["双方同意且可随时退出，是重要反证。", "Mutual consent with a real opt-out is important counterevidence."]),
  rule("R17", "跟踪/网络跟踪", "stalking / cyberstalking", [/(明确拒绝|不受欢迎).{0,40}(持续联系|换号|尾随|定位|住处等候)|反复.{0,18}(尾随|到住处|换号联系|定位)|after refusal.{0,24}(contact|follow|track)/i], [/(一次|只发一次).{0,12}(事务|归还物品|联系)|one message.{0,12}return/i], "high", ["拒绝后仍重复接触、监控或到场，并造成恐惧或干扰。", "Contact or monitoring continues after refusal and causes fear or disruption."], ["一次事务联系不满足跟踪的重复性门槛。", "One practical contact does not meet the repetition threshold for stalking."]),
  rule("R18", "武器/可信人身威胁", "weapon / credible bodily threat", [/(带枪|持刀|杀了你|弄死你|锁门不让走|强制带回|性强迫|weapon|gun.{0,8}(come|find)|kill you|confine|sexual force)/i], [/(电影|影视|小说|角色).{0,10}(枪|杀)|film|fictional character/i], "urgent", ["原文出现可信且可能迫近的人身、武器、拘禁或性危险。", "The text contains a credible and potentially imminent bodily, weapon, confinement, or sexual threat."], ["此时优先处理现实安全，不等待更多关系模式。", "Prioritise immediate safety rather than waiting for more relational evidence."]),
  rule("R19", "一次性工作反馈", "one-off work feedback", [/(报告|任务).{0,16}(缺少|需要).{0,18}(数据|来源|周五|补充)|specific feedback|missing data|deadline/i], [/(蠢|废物|公开羞辱|报复|stupid|humiliat|retaliat)/i], "low", ["反馈具体、可执行，并指向任务标准。", "The feedback is specific, actionable, and tied to work standards."], ["语气可以改进，但一次具体反馈不等于霸凌。", "Tone may need improvement, but one concrete feedback event is not bullying."]),
  rule("R20", "职场霸凌", "workplace bullying", [/(连续|数月|反复|长期).{0,20}(公开羞辱|排斥|不给资料|不可能期限|提高要求|报复)|months.{0,16}(humiliat|exclude|retaliat)|repeatedly.{0,16}(shifting standards|sabotage)/i], [/(一次|偶发).{0,12}(反馈|加班|争执)|one-off feedback|single incident/i], "high", ["负面行为持续重复，并与权力差或难以防御的工作后果相连。", "Negative conduct is repeated and tied to power imbalance or hard-to-defend work consequences."], ["一次具体反馈不足以使用职场霸凌强标签。", "One concrete feedback event is insufficient for the strong bullying label."]),
  rule("R21", "虐待型监督", "abusive supervision", [/(主管|老板|领导).{0,18}(持续|反复).{0,14}(贬低|嘲讽|公开羞辱|威胁|任意惩罚)|manager.{0,16}(repeatedly|continuously).{0,12}(ridicule|humiliat|threat)/i], [/(明确标准|一次情绪失控后道歉|clear standard|repaired)/i], "high", ["主管持续使用敌意、羞辱或任意惩罚，而非管理标准。", "A supervisor repeatedly uses hostility, humiliation, or arbitrary punishment rather than work standards."], ["权力和持续性是判断重点。", "Power and persistence are central to this distinction."]),
  rule("R22", "职场煤气灯", "workplace gaslighting", [/(主管|领导).{0,18}(多次|反复).{0,14}(否认书面承诺|改写指令|说你记忆有问题)|manager.{0,16}(repeatedly denied|rewrote instructions)/i], [/(政策更新|新版文档|承认旧说法)|policy update|acknowledged the old version/i], "pressure", ["书面承诺或指令被反复改写，同时下属的记忆或能力被贬低。", "Written commitments or instructions are repeatedly rewritten while the employee's memory or competence is attacked."], ["先核对书面记录，不必推断主管的人格。", "Check written records without inferring the supervisor's personality."]),
  rule("R23", "分手/关系退出", "relationship exit", [/(决定结束关系|不能继续|不再联系|删除联系方式|祝你幸福|end the relationship|cannot continue|no further contact|wish you well)/i], [/(不答应|不听话).{0,10}(就分手|离开你)|unless you.{0,8}break up/i], "low", ["对方在表达关系退出；退出权本身不等于操控。", "The person is ending the relationship; the right to leave is not manipulation by itself."], ["可以分别看结束决定和解释是否具体。", "Separate the decision to leave from how clearly it is explained."]),
  rule("R24", "模糊自责/关闭讨论", "vague self-blame / closure", [/(都是我的错|都是我的原因|我不好).{0,18}(别问|祝你|结束)|all my fault.{0,16}(don't ask|goodbye)/i], [/(具体|因为).{0,20}(失约|回避|伤害|原因)|because I.{0,18}(failed|avoided|hurt)/i], "notice", ["看似承担责任，但没有留下可核对的具体行为或原因。", "It sounds accountable but leaves no concrete behaviour or reason to examine."], ["模糊自责不必被当成完整解释。", "Vague self-blame need not be treated as a complete explanation."]),
  rule("R25", "关系历史重写", "relationship history rewrite", [/(交流不深|沟通不好).{0,18}(从来不是爱|不是爱|只是冲动|一切是假的)|never loved|only an impulse|was never real/i], [/(过去.{0,10}(真实|有感情).{0,14}(现在|但).{0,8}(无法继续|结束))|past was real/i], "notice", ["当前困难被直接推成对过去关系的整体否定。", "A current difficulty is used to negate the entire history of the relationship."], ["对方有权结束关系，但不自动证明过去全部虚假。", "Someone may leave without proving the whole past was false."]),
  rule("R26", "消费标准定义权", "authority to define spending", [/(什么算合理|生存需要|高消费).{0,18}(由我定|你要|不许|不能)|你自己的钱.{0,10}(不许|不能)|I decide.{0,12}(reasonable|spending)/i], [/(共同制定|双方同一标准|个人额度|今年储蓄目标)|same standard|personal allowance/i], "notice", ["需要核对谁定义“合理”，以及同一标准是否也约束定义规则的人。", "Check who defines 'reasonable' and whether the same standard applies to the rule-maker."], ["共同预算不等于一方单独审查另一方的个人钱。", "Shared budgeting does not mean unilateral review of the other's personal money."]),
  rule("R27", "生育成本议题错位", "pregnancy-cost issue displacement", [/(生育|怀孕|身体|职业|机会成本).{0,35}(男(生|方|人)也辛苦|也要养家|退休更晚|men also work hard)/i], [/(先把|分别).{0,16}(身体|职业|照护).{0,16}(成本|列清)|list.{0,12}pregnancy costs/i], "notice", ["另一类辛苦没有直接回应身体、职业和机会成本如何分配。", "Another form of hardship does not answer how bodily, career, and opportunity costs are shared."], ["双方都辛苦可以同时成立，不需要互相抵销。", "Both forms of hardship can be real without cancelling each other."]),
  rule("R28", "单向社交融合", "one-way social integration", [/(先|只).{0,8}(和|见).{0,8}(我的朋友|我朋友)|少见.{0,8}(自己的朋友)|join my friends first|see your friends less/i], [/(我也|双方|轮流).{0,10}(见|认识).{0,8}(你的朋友|彼此朋友)|I'll meet your friends/i], "notice", ["亲密和朋友圈融合被优先安排成单向进入一方生活。", "Closeness and social integration are arranged mainly around one person's life."], ["希望陪伴可以合理；仍要核对融合是否双向。", "Wanting closeness can be reasonable; reciprocity still matters."]),
  rule("R29", "平等口号与实际安排", "equality claim versus arrangements", [/(男女平等|双方义务一致|很自由).{0,45}(女方负责|彩礼.{0,8}带回|只要求|默认女方|equal.{0,30}(woman|wife).{0,12}(must|responsible))/i], [/(按时间和能力|生育期重新调整|双方同意|adjust during pregnancy)/i], "notice", ["平等口号需要与家务、生育、职业、父母和财产的具体安排逐项对照。", "Equality claims need to match concrete arrangements for care, work, parents, and property."], ["原则是否平等，要看实际成本和例外如何分配。", "Equality is shown by how real costs and exceptions are shared."]),
  rule("R30", "赠与/共同购房/产权含混", "gift / joint purchase / ownership ambiguity", [/(彩礼|家庭出资|个人钱).{0,18}(带回|补进|用于).{0,10}(购房|买房).{0,24}(产权|登记|比例|没说|不清)?|bride price.{0,20}(house|property)/i], [/(明确|写清).{0,12}(出资|登记|产权|比例|退出)|ownership proportion|written agreement/i], "notice", ["资金被预设进入共同购房，但赠与性质、产权比例或退出安排仍不清楚。", "Money is presumed to enter a joint purchase while gift status, ownership, or exit terms remain unclear."], ["先区分赠与、个人财产、共同资金和产权。", "Separate gifts, personal property, joint funds, and ownership."]),
  rule("R31", "提前预算伴侣资源", "pre-allocation of partner resources", [/(我以后|我要).{0,12}(买|要).{0,8}(车|房).{0,16}(你帮我|你补|你出)|your money.{0,12}(my car|my house)/i], [/(共同用|按产权|按使用|双方同意).{0,14}(出资|承担)|shared use|agreed contribution/i], "notice", ["一方的未来资源被预先纳入另一方的个人资产安排。", "One partner's future resources are pre-allocated to the other's personal asset."], ["需要核对这是共同目标，还是先替对方的钱作了决定。", "Clarify whether this is a shared goal or a unilateral plan for the other's money."]),
  rule("R32", "支出比例与无偿贡献", "contribution ratios and unpaid work", [/(三六分|固定.{0,6}比例|女方必须出|不能完全不支出).{0,30}(收入|产权|家务|照护|生育|失业)?|fixed contribution ratio/i], [/(按收入|产权|家务|照护|生育阶段|失业).{0,18}(调整|计算)|adjust by income|unpaid care/i], "notice", ["固定比例需要说明收入、产权、家务、照护、生育和失业阶段如何计入。", "A fixed ratio needs an account of income, ownership, unpaid care, pregnancy, and unemployment stages."], ["参与共同支出可以合理，比例依据仍应透明。", "Contributing can be reasonable while the basis for the ratio remains transparent."]),
  rule("R33", "事实修正被忽略", "ignored factual correction", [/(用户|我).{0,18}(补充|说明|说).{0,20}(本地|同城|来合肥|不是外地).{0,40}(仍|还是|继续).{0,16}(外地|很远|旧指控)|already said.{0,18}(same city|local).{0,20}still/i], [/(听到|根据|既然).{0,12}(新事实|本地|同城).{0,16}(调整|仍担心具体)|updated concern/i], "notice", ["用户补充的新事实没有进入后续讨论，旧指控继续被沿用。", "The user's correction does not enter the later discussion; the old accusation continues."], ["先确认哪一条新事实仍未被回应。", "Identify which corrected fact remains unanswered."]),
  rule("R34", "添加指控/稻草人", "added accusation / straw person", [/(只说|提出|打算).{0,18}(见面|讨论|安排).{0,28}(却|被说成).{0,16}(逼|勾来|对付|背叛)|把人勾来|给你出主意来对付我们|you meant to.{0,12}(force|betray)/i], [/(你是想|我担心是否|是不是).{0,14}(见面|安排|意思)|are you asking/i], "pressure", ["没有表达过的意图被加到用户身上，再围绕这个版本责骂。", "An unstated intention is assigned to the user and then attacked."], ["区分原话、合理推断和需要提问核对的意图。", "Separate stated words, supported inference, and intentions that require clarification."]),
  rule("R35", "后果威胁/灾难化预测", "consequence threat / catastrophising", [/(后果自负|走着看|试试看|你会后悔|没人要你|face the consequences|you'll regret|wait and see)/i], [/(罚金|法律后果|现实风险).{0,16}(明确|一起评估)|specific consequence|verifiable risk/i], "pressure", ["模糊或灾难化后果被用来让拒绝显得危险。", "Vague or catastrophic consequences are used to make refusal feel dangerous."], ["具体可核对的风险提醒，与对方可施加的惩罚不同。", "A verifiable risk is different from punishment the speaker may impose."]),
  rule("R36", "风险等级", "risk calibration", [/[\s\S]+/], [], "meta", ["风险按行为证据、重复、权力和迫近性校准。", "Risk is calibrated from behaviour, repetition, power, and imminence."], ["高或紧急需要直接行为证据。", "High or urgent risk requires direct behavioural evidence."]),
  rule("R37", "冲突消解/去重", "conflict resolution / deduplication", [/[\s\S]+/], [], "meta", ["同一证据保留一个主解释，近义机制合并。", "Each piece of evidence keeps one primary explanation; overlapping mechanisms are merged."], ["没有新增信息就不增加卡片。", "Do not add a card without new information."]),
  rule("R38", "证据边界/不确定性", "evidence boundary / uncertainty", [/[\s\S]+/], [], "meta", ["区分可观察事实、有依据推断和真正影响结论的未知。", "Separate observable facts, supported inference, and unknowns that would change the conclusion."], ["不确定性要具体，不能抹去已经发生的行为。", "Uncertainty should be specific and must not erase observed behaviour."]),
];

export function ruleText(ruleId: string, language: AnalysisLanguage) {
  return RESEARCH_RULES.find((item) => item.id === ruleId)?.construct[language] || ruleId;
}
