"use client";

import { useState } from "react";

const patterns = [
  { title:"Making you doubt yourself", words:["too sensitive","imagining things","never said that","remember it wrong","overreacting","crazy"], note:"The focus shifts from what happened to whether there’s something wrong with you." },
  { title:"Putting you down", words:["useless","stupid","no one wants you","pathetic","embarrassing","not good enough"], note:"That’s a personal attack, not useful feedback." },
  { title:"Pressure dressed up as love", words:["if you loved me","doing this for you","after all i've done","you owe me","prove you love me"], note:"Care doesn’t cancel consent or your right to say no." },
  { title:"Control and isolation", words:["send your location","stop seeing them","don't talk to","check your phone","give me your password","not allowed to leave"], note:"Cutting off people, money, movement or privacy can make it harder to choose freely." },
  { title:"Blame reversal", words:["you made me do it","this is your fault","i'm the real victim","you're abusing me","look what you did"], note:"They may be dodging the original harm by denying it, attacking you, then swapping victim and offender." },
  { title:"Punishing silence", words:["don't contact me","i'll ignore you","talk when you admit","until you apologise","you need to reflect"], note:"A healthy break has a reason and a time to reconnect. Silence used to force surrender is different." },
  { title:"Workplace bullying signs", words:["do it tonight","you'll never pass probation","not invited to the meeting","don't copy them","take the credit","you'll never work in this industry","quit if you can't"], note:"One rough day isn’t proof. Watch for repeated humiliation, blocked information, impossible work or retaliation." },
  { title:"Friendship betrayal or exclusion", words:["everyone knows","we didn't invite you","no one likes you","keep this between us","i told them about you","they all agree with me","choose me or them"], note:"A row can happen in any friendship. Repeated gossip, public shaming, exclusion or turning the group against you is different." },
];

export default function EnglishChecker() {
  const [context,setContext]=useState("Partner / dating"); const [text,setText]=useState(""); const [done,setDone]=useState(false);
  const lower=text.toLowerCase(); const findings=patterns.map((item)=>({...item,hits:item.words.filter((word)=>lower.includes(word))})).filter((item)=>item.hits.length);
  const replies=context === "Work" ? ["Just to confirm, could you put the deadline, priority and expected standard in writing?","I’m happy to discuss the work. Please keep the feedback to the task, not my character.","If the scope has changed, please update it in writing so I can re-prioritise."] : ["Let’s stick to what happened. I’m not discussing my character.","I hear you, but I won’t keep talking while I’m being insulted or threatened.","I’m taking some space. I’ll reply when I feel safe and clear."];
  return <section className="english-tool" id="check"><div className="section-heading"><p className="eyebrow">Chat clarity</p><h2>Drop the chat here. We’ll unpack it.</h2><p>No diagnosis. No guessing. Just the words, the pressure, and what you can do next.</p></div><div className="english-context">{["Partner / dating","Family","Work","Friend"].map((item)=><button className={context===item?"active":""} onClick={()=>setContext(item)} key={item}>{item}</button>)}</div><textarea value={text} onChange={(e)=>{setText(e.target.value.slice(0,12000));setDone(false);}} placeholder="Paste the messages here. Remove names, numbers and addresses first."/><button className="primary" disabled={text.trim().length<8} onClick={()=>setDone(true)}>Have a look</button>{done&&<div className="english-result"><span>{context}</span><h3>{findings.length?"A few things don’t sit right":"Not enough here to call a clear pattern"}</h3><p>{findings.length?"You don’t need to prove you’re ‘good enough’ before talking about facts and boundaries. One message can’t define a whole relationship, so check what keeps happening — and what happens when you say no.":"That doesn’t mean your feelings are wrong. Add a bit more context, especially what happened after you said no or asked for clarity."}</p>{findings.map((item)=><article key={item.title}><b>{item.title}</b><small>Matched: {item.hits.join(", ")}</small><p>{item.note}</p></article>)}<h4>If you want to reply</h4>{replies.map((reply)=><button className="copy-reply" onClick={()=>navigator.clipboard?.writeText(reply)} key={reply}>{reply}<small>Copy</small></button>)}</div>}</section>;
}
