import Link from "next/link";
import ThemeControls from "../components/theme-controls";

type Topic = { id: string; icon: string; title: string; looks: string[]; confusing: string; notProof: string; matters: string; example: string; response: string; source: string };
const topics: Topic[] = [
  { id: "gaslighting", icon: "🪞", title: "Gaslighting and denial", looks: ["A clear event is repeatedly denied", "Small memory gaps are used to dismiss the whole concern"], confusing: "It can leave you arguing about your memory instead of the behaviour.", notProof: "People can remember one event differently.", matters: "A repeated pattern of denial, attack and refusal to check facts together.", example: "‘I never said that. You always invent things.’", response: "Keep one dated note with the original words and any record that helps you check them.", source: "https://www.thehotline.org/resources/what-is-gaslighting/" },
  { id: "humiliation", icon: "🥀", title: "Humiliation and devaluation", looks: ["Mocking your ability, body or worth", "Calling a hurtful comment a joke after you object"], confusing: "A joke can make you doubt whether you are allowed to be hurt.", notProof: "One clumsy comment followed by a real apology and changed behaviour.", matters: "Repeated personal attacks that make you smaller or quieter.", example: "‘No one else would put up with you.’", response: "Name the behaviour once: ‘Do not speak to me like that.’ Then watch whether it stops.", source: "https://www.thehotline.org/resources/types-of-abuse/" },
  { id: "control", icon: "🕊️", title: "Isolation and coercive control", looks: ["Pressure around location, passwords, money or work", "Making support networks harder to reach"], confusing: "It may be presented as protection, love or practical help.", notProof: "Freely chosen sharing that can be refused without punishment.", matters: "Whether saying no leads to punishment, surveillance or less freedom.", example: "‘Send your live location, or you must be hiding something.’", response: "Check sharing permissions and keep one trusted person outside the situation informed.", source: "https://womensaid.org.uk/information-support/what-is-domestic-abuse/coercive-control/" },
  { id: "coercion", icon: "⛈️", title: "Threats and emotional coercion", looks: ["Threatening breakup, self-harm, exposure or retaliation", "Using a crisis to make you decide immediately"], confusing: "Care for someone can make it feel impossible to step back.", notProof: "A person naming distress and accepting real help without making you responsible.", matters: "Whether the threat is used to remove your choice or isolate you.", example: "‘If you leave, I will hurt myself and it will be your fault.’", response: "Tell a local trusted adult or emergency support if risk is immediate; do not carry the crisis alone.", source: "https://www.thehotline.org/resources/when-my-partner-threatens-suicide/" },
  { id: "darvo", icon: "🎭", title: "DARVO and reactive behaviour", looks: ["A concern is denied, then you are attacked, then roles are reversed", "Only your final reaction is shown to others"], confusing: "Long pressure can lead to panic, anger or shutdown, which may be used against you.", notProof: "Strong feelings alone do not show who caused a pattern.", matters: "The full timeline, power difference, repeated behaviour and response to a boundary.", example: "‘You are the abusive one’ after you raise a specific harm.", response: "Write a short sequence: what happened before, what you said, what they did, and what happened after.", source: "https://pubmed.ncbi.nlm.nih.gov/37154429/" },
  { id: "silence", icon: "🌫️", title: "Silent treatment versus healthy space", looks: ["Disappearing until you apologise", "Withdrawing warmth as a punishment"], confusing: "Everyone needs space sometimes.", notProof: "A pause with a reason, a time to reconnect and no demand for surrender.", matters: "Whether silence is used repeatedly to force compliance.", example: "‘I will speak to you only when you admit you were wrong.’", response: "Ask once for a return time, then stop chasing and use the time to ground yourself.", source: "https://www.gottman.com/blog/the-silent-treatment/" },
  { id: "workplace", icon: "🗂️", title: "Workplace mobbing", looks: ["Information is withheld and then your work is blamed", "Public shaming, exclusion or moving standards"], confusing: "Busy workplaces and bad management are real too.", notProof: "One clear, proportionate performance conversation.", matters: "Repeated negative conduct, power imbalance and difficulty stopping it.", example: "A meeting is withheld, then you are criticised for missing its decisions.", response: "Confirm task, deadline, resources and criteria in writing; save changes by date.", source: "https://www.cdc.gov/niosh/work-related-stress/about/index.html" },
  { id: "financial", icon: "💳", title: "Financial abuse", looks: ["Controlling access to money, work, cards or documents", "Creating debt or dependence as a condition of staying"], confusing: "Financial help can look caring from the outside.", notProof: "Agreed shared finances with equal access and the freedom to leave.", matters: "Whether resources are used to reduce your independence.", example: "‘You cannot work. Give me your card and I will manage everything.’", response: "Keep copies of key documents and one independent way to access funds if it is safe.", source: "https://nnedv.org/content/about-financial-abuse/" },
  { id: "digital", icon: "📱", title: "Digital surveillance", looks: ["Demanding passwords or live location", "Checking devices, accounts or messages"], confusing: "It may be framed as transparency.", notProof: "Voluntary sharing that is easy to revoke without consequences.", matters: "Monitoring, coercion, hidden access and retaliation after privacy is requested.", example: "‘If you trust me, I should be able to read every message.’", response: "Review account sessions, location sharing and recovery email from a safe device.", source: "https://www.techsafety.org/resources-survivors" },
  { id: "friendship", icon: "🫂", title: "Friendship betrayal and exclusion", looks: ["Sharing private information or screenshots", "Group exclusion, gossip or loyalty tests"], confusing: "Friendships can drift naturally.", notProof: "A disagreement or distance that stays respectful and does not recruit others.", matters: "Planned humiliation, exposure, triangulation or repeated isolation.", example: "‘Choose us or them — and we will show everyone what you said.’", response: "Save the original record and explain the full sequence once to one trusted person outside the group.", source: "https://www.apa.org/topics/friendships" },
  { id: "trauma", icon: "🌱", title: "Trauma responses", looks: ["Hypervigilance, numbness, panic, sleep changes or replaying events"], confusing: "Your body can stay on alert after pressure ends.", notProof: "A web page cannot diagnose trauma or a disorder.", matters: "Whether symptoms persist, affect daily life or make safety harder.", example: "A notification sound triggers a racing heart long after a difficult relationship.", response: "Track sleep and body responses for a few days and consider professional support if daily life is affected.", source: "https://www.nimh.nih.gov/health/topics/coping-with-traumatic-events" },
];

export default function LearnPage() { return <main><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">G</span><span>Grow Into Yourself</span></Link><nav><Link href="/">Home</Link><Link href="/#self-check">Relationship check</Link><Link href="/#check">Check a chat</Link><Link href="/zh/learn">中文</Link></nav><ThemeControls /></header><section className="learn-library"><div className="learn-library-hero"><p className="eyebrow">A practical guide</p><h1>Name the pattern. Keep the nuance.</h1><p>These pages explain observable behaviour. They do not diagnose a person or tell you what decision to make.</p></div><div className="topic-index">{topics.map((topic) => <a href={`#${topic.id}`} key={topic.id}><span>{topic.icon}</span>{topic.title}</a>)}</div><div className="topic-list">{topics.map((topic, index) => <article id={topic.id} key={topic.id}><div className="topic-number">{String(index + 1).padStart(2, "0")} {topic.icon}</div><h2>{topic.title}</h2><div className="topic-columns"><div><h3>What it can look like</h3><ul>{topic.looks.map((item) => <li key={item}>{item}</li>)}</ul><h3>Why it feels confusing</h3><p>{topic.confusing}</p></div><div><h3>What does not prove abuse</h3><p>{topic.notProof}</p><h3>What repeated patterns matter</h3><p>{topic.matters}</p></div><div><h3>A realistic example</h3><p>{topic.example}</p><h3>A practical response</h3><p>{topic.response}</p><a href={topic.source} target="_blank" rel="noreferrer">Source →</a></div></div></article>)}</div><section className="source-library" id="sources"><p className="eyebrow">Sources and limits</p><h2>Read the source, keep the context.</h2><p>These summaries draw on public health, safety and research resources. They are not validated diagnostic tests and cannot replace local professional support.</p></section></section><footer><strong>Grow Into Yourself</strong><span>Observe behaviour. Keep your choices.</span><Link href="/">Back to home</Link></footer></main>; }
