import Link from "next/link";
import ThemeControls from "../../components/theme-controls";

const topics = [
  { id:"gaslighting", icon:"🪞", title:"总说“你记错了”，就一定是煤气灯效应吗？", simple:"不是一次记错，而是你每次提出问题，都被带到“是不是你脑子有问题”。", signs:["否认明明发生过的事","抓住你记不清的小地方，推翻整件事","让你越来越依赖对方告诉你什么是真的"], boundary:"两个人记忆不同很常见。真正要看的是：对方愿不愿意一起核对事实，还是反复攻击你的判断力。", step:"新建一条只给自己看的记录，固定写四栏：日期时间｜对方原话｜当时能核对的截图或账单｜这件事造成的后果。保留完整上下文，不只截最激烈的一句。" },
  { id:"humiliation", icon:"🥀", title:"“我只是开玩笑”，为什么还是很受伤？", simple:"玩笑让双方都能笑。羞辱是一个人开心，另一个人越来越小。", signs:["攻击外貌、智力、家庭或价值","在别人面前让你难堪","你说不舒服后，反过来说你玻璃心"], boundary:"偶尔说错话不等于长期虐待；道歉、停止和改变，比“我没恶意”更重要。", step:"只说一次具体边界：“刚才拿我的___开玩笑，我不接受。再出现我会结束这次聊天。”随后记录对方是停止并修正，还是继续嘲笑、追骂或拉别人围观。" },
  { id:"control", icon:"🕊️", title:"关心和控制，差在哪里？", simple:"关心会问你想不想；控制会让你不敢说不。", signs:["要求定位、密码、查手机","限制朋友、工作、钱、证件或出行","把生活资源变成服从条件"], boundary:"共享位置或共同理财本身不是控制。关键是能否自由拒绝，拒绝后会不会被惩罚。", step:"在对方接触不到的安全位置保存身份证件复印件、一个紧急联系人和少量可独立使用的钱。如果对方会查手机，不要把计划留在共用设备或显眼聊天里。" },
  { id:"darvo", icon:"🎭", title:"为什么对方很冷静，我却像“疯了”？", simple:"外人常只看到最后五分钟，却没看到前面几个月的否认、逼迫和积累。", signs:["你指出伤害，对方先否认","接着攻击你的性格、情绪或可信度","最后把自己说成受害者，只展示你崩溃的片段"], boundary:"情绪崩溃值得理解，但不代表辱骂或伤害自动合理；同样，语气平静也不能证明行为无害。", step:"按“冲突前发生什么→你提出什么→对方原话→你何时开始失控→对方展示了哪一段→事后谁承担后果”写成一页时间线，请一个不在冲突圈里的人只看完整顺序。" },
  { id:"silence", icon:"🌫️", title:"需要冷静，和用沉默惩罚，有什么不同？", simple:"健康暂停会告诉你原因和什么时候回来；惩罚性沉默是在等你投降。", signs:["突然消失又拒绝说明","恢复联系的条件是你认错或服从","反复撤回亲密，让你害怕被抛下"], boundary:"每个人都有暂时不说话的权利。区别在是否说明、是否约定恢复、是否把沉默当控制工具。", step:"发一条就停：“我尊重你暂停。请在明晚8点前告诉我是否愿意继续谈；没有回复，我会按暂不沟通安排自己的时间。”到点后不要连发追问，记录对方是否只在你妥协后恢复联系。" },
  { id:"npd", icon:"🧩", title:"自恋、NPD和“坏人”不是一回事", simple:"自恋特质人人可能有；NPD是需要专业人员直接评估的长期临床模式。", signs:["长期夸大自身重要性或特权","非常需要赞美，难以承受质疑","关系中缺少互惠、利用他人或共情困难"], boundary:"一段截图不能诊断NPD；确诊NPD也不等于一定暴力。真正需要处理的是已经发生的伤害和边界。", step:"先不写“NPD”。选一个可观察行为，例如辱骂或查手机，记录过去四周发生几次、你拒绝后怎样升级、是否真正停止。用这张行为记录决定边界，而不是等一个诊断。" },
  { id:"danger-labels", icon:"🧭", title:"所谓“恐怖人格”，为什么容易误导？", simple:"危险不是由一个流行标签决定，而要看威胁、跟踪、武器、限制自由和行为升级。", signs:["把所有冷漠都叫反社会人格","把情绪强烈都叫边缘型人格","用人格标签替代具体证据和安全判断"], boundary:"人格障碍患者并不自动危险；把疾病和暴力画等号会制造污名，也可能漏掉没有诊断但行为很危险的人。", step:"逐项回答五个事实：有没有明确威胁、跟踪定位、接触武器、堵门扣证件、近期升级。写下时间和原话；任一项正在发生时，先联系可信的人和现实安全支持，不等人格测试结果。" },
  { id:"friendship", icon:"🫂", title:"朋友背叛，为什么也会像失恋？", simple:"友情里也有依恋、信任和共同身份。泄密、排挤或集体背叛会带来真实的哀伤。", signs:["公开秘密、截图或隐私","拉群、传话、逼共同朋友选边","需要你时亲密，设边界后集体孤立"], boundary:"朋友自然疏远不等于霸凌；有计划地羞辱、造谣、围攻和切断支持需要认真对待。", step:"先保存原帖、群聊和转发链，修改被对方知道的密码与可见范围。只向一位关键当事人发一次简短更正：“完整经过是___，原始记录在这里。”不要在多个群里循环自证。" },
  { id:"workplace", icon:"🗂️", title:"严格管理和职场霸凌，怎么分？", simple:"严格管理有清楚标准；霸凌让标准不断移动，让你注定失败。", signs:["扣住信息再责怪你做不好","公开羞辱、抢功、造谣或排除会议","用绩效、排班、转正或行业名声报复"], boundary:"一次批评或紧急任务不自动等于霸凌。研究更看重反复负面行为、权力不对等和难以制止。", step:"口头交办后发书面确认：“确认今天的要求：交付物___，截止___，需要资源___，验收标准___。如有不同请今天回复。”同时按日期保存标准变化、排除会议和目击者。" },
  { id:"body", icon:"🌱", title:"为什么离开后，身体还是很紧张？", simple:"危险结束了，身体的警报不一定马上关掉。失眠、胃痛、心慌和反复回想都可能出现。", signs:["看到消息就心跳加快","不停复盘，害怕自己判断错","麻木、易怒、注意力下降或睡不好"], boundary:"这些反应不证明你“疯了”，也不能只靠网页诊断创伤后应激。持续影响生活时应考虑专业评估。", step:"连续三天只做四项并打勾：固定起床时间、吃两顿正餐、走路10分钟、和可信的人联系一次；另记睡眠时长与最强身体反应。连续两周明显影响生活，带记录去做专业评估。" },
];

const papers = [
  ["强制控制与创伤、抑郁综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC10666508/"], ["亲密关系中的隐性/隐蔽虐待综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC11545147/"], ["新兴成人期煤气灯效应暴露研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC11456334/"], ["DARVO与当事人可信度研究","https://www.tandfonline.com/doi/full/10.1080/10926771.2020.1774695"], ["DARVO与不真诚道歉研究","https://pubmed.ncbi.nlm.nih.gov/37154429/"], ["NPD理解与治疗进展综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC10187400/"], ["职场霸凌风险因素系统综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC6603960/"], ["NAQ-R职场霸凌测量研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC6292423/"], ["职场排斥与健康影响研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC10451850/"], ["技术促成的亲密关系虐待综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC10486147/"], ["累积创伤、背叛与认知评价研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC3608140/"], ["制度背叛生态综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC11545134/"], ["在线同伴支持风险与收益研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC10015351/"], ["在线心理社区中的审核者作用","https://pmc.ncbi.nlm.nih.gov/articles/PMC9933803/"], ["myPlan安全决策工具适配研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC7260790/"], ["大学女性约会暴力安全App研究","https://pmc.ncbi.nlm.nih.gov/articles/PMC4563945/"], ["在线心理同伴支持效果与体验综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC12935419/"], ["受虐青少年友情与心理健康系统综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC11427613/"], ["心理型亲密伴侣暴力与PTSD研究","https://pubmed.ncbi.nlm.nih.gov/35948921/"], ["亲密伴侣暴力与压力相关障碍综述","https://pmc.ncbi.nlm.nih.gov/articles/PMC12104246/"],
];
const guides = [
  ["WHO：精神健康与精神障碍","https://www.who.int/news-room/fact-sheets/detail/mental-disorders"], ["CDC：亲密伴侣暴力基础资料","https://www.cdc.gov/intimate-partner-violence/about/index.html"], ["WHO：工作场所精神健康","https://www.who.int/news-room/fact-sheets/detail/mental-health-at-work"], ["myPlan：循证安全决策工具的设计依据","https://myplanapp.org/en/our-story"], ["NIMH：精神健康主题资料","https://www.nimh.nih.gov/health/topics/mental-illnesses"], ["UN Women：终止针对女性的暴力","https://www.unwomen.org/en/what-we-do/ending-violence-against-women"],
];

export default function LearnPage() {
  return <main className="zh-page"><header className="topbar"><Link className="brand" href="/zh"><span className="brand-mark">长</span><span>长成自己</span></Link><nav><Link href="/zh">返回首页</Link><Link href="/zh#self-check">关系自查</Link><Link href="/zh#tool">拆解聊天</Link><Link href="/learn">English</Link></nav><ThemeControls language="zh" /></header>
    <section className="learn-library"><div className="learn-library-hero"><p className="eyebrow">给第一次接触心理学的你</p><h1>不用懂术语，也能看懂一段关系发生了什么</h1><p>这里不教你隔着屏幕给别人确诊。我们把复杂概念翻成能观察、能记录、能保护自己的小问题。</p></div><div className="topic-index">{topics.map((topic) => <a href={`#${topic.id}`} key={topic.id}><span>{topic.icon}</span>{topic.title}</a>)}</div>
      <div className="topic-list">{topics.map((topic, index) => <article id={topic.id} key={topic.id}><div className="topic-number">{String(index + 1).padStart(2,"0")} {topic.icon}</div><h2>{topic.title}</h2><p className="simple-answer">{topic.simple}</p><div className="topic-columns"><div><h3>它可能长这样</h3><ul>{topic.signs.map((sign) => <li key={sign}>{sign}</li>)}</ul></div><div><h3>别急着下结论</h3><p>{topic.boundary}</p></div><div><h3>具体可以怎么做</h3><p>{topic.step}</p></div></div></article>)}</div>
      <section className="source-library" id="sources"><p className="eyebrow">依据与边界</p><h2>这页不是凭感觉写的</h2><p>本轮改版检索核对了60余条学术、机构与同类循证产品资料；页面首批公开26项直接来源，包括20篇国际同行评审论文/综述和6项权威机构或循证工具资料。我们对原文做了通俗改写，不把它们冒充本项目已经完成效度验证的诊断量表。</p><details><summary>查看20篇国际论文与综述</summary><ol>{papers.map(([title,url]) => <li key={url}><a href={url} target="_blank" rel="noreferrer">{title}</a></li>)}</ol></details><details><summary>查看6项机构与循证工具资料</summary><ol>{guides.map(([title,url]) => <li key={url}><a href={url} target="_blank" rel="noreferrer">{title}</a></li>)}</ol></details></section>
    </section><footer><strong>长成自己</strong><span>理解行为，不滥用诊断 · 情绪大小不等于对错</span><Link href="/zh">返回首页</Link></footer></main>;
}
